# basic options
title: Zheng "Leslie" CHEN
author: Zheng CHEN
email: zchen2@umassd.edu
description: A wonderful site
#twitter_username: 
#github_username:  

# Build settings
markdown: kramdown
theme: minima
