# basic options
title: Personal website
author: Zheng "Leslie" Chen
email: zchen2@umassd.edu
description: A wonderful site
#twitter_username: 
#github_username:  

# Build settings
markdown: kramdown
theme: minima
